### PR TITLE
Fix incompatibility with Vagrant 1.7.2

### LINKED ISSUE #6: Why am i having this error on version 0.1.8 ?
Since i installed version 0.1.8, when run (vagrant up mymachine) shows this error below:

Bringing machine 'mymachine' up with 'virtualbox' provider...
/home/samuel/.vagrant.d/gems/gems/vagrant-ohai-0.1.8/lib/vagrant-ohai/helpers.rb:7:in `block in chef_provisioners': undefined method `type' for #<VagrantPlugins::Kernel_V2::VagrantConfigProvisioner:0x00000001d78448> (NoMethodError)
	from /home/samuel/.vagrant.d/gems/gems/vagrant-ohai-0.1.8/lib/vagrant-ohai/helpers.rb:6:in `each'
	from /home/samuel/.vagrant.d/gems/gems/vagrant-ohai-0.1.8/lib/vagrant-ohai/helpers.rb:6:in `find_all'
	from /home/samuel/.vagrant.d/gems/gems/vagrant-ohai-0.1.8/lib/vagrant-ohai/helpers.rb:6:in `chef_provisioners'
	from /home/samuel/.vagrant.d/gems/gems/vagrant-ohai-0.1.8/lib/vagrant-ohai/action_configure_chef.rb:33:in `register_custom_chef_config'
	from /home/samuel/.vagrant.d/gems/gems/vagrant-ohai-0.1.8/lib/vagrant-ohai/action_configure_chef.rb:13:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:90:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:90:in `finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:20:in `block in initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:20:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:20:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:170:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:170:in `to_app'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

Am i doing something wrong ?

At version 0.1.7 works perfectly!

$ vagrant --version
Vagrant 1.6.5

### PR DESCRIPTION
**Pull request by estahn**
Fix #6 and #11

### CODE REVIEW

**Comment by gshively11** [comment]
:+1: for the backwards compatibility that my PR doesn't have.

**Comment by zeroem** [comment]
:+1:

**Comment by kongslund** [comment]
Excellent fix.

@avishai-ish-shalom When are you planning to make a new release of the plugin including this fix?

**Comment by avishai-ish-shalom** [comment]
yep, today

**Comment by avishai-ish-shalom** [comment]
version 0.1.12 released

**Pull request merged**
